config/routes.rb
Rails.application.routes.draw do
   
  devise_for :users
  resources :discounts
  resources :payments
  resources :payment_items

  resources :companies
  resources :projects do
    resources :tasks
  end	
  
  get 'all-tasks', to: "tasks#all_tasks"
  
  get 'get/pdf', to: "projects#get_pdf", as: :get_pdf
  get 'get/xls', to: "projects#get_xls", as: :get_xls
  
  get 'get/tasks_pdf', to: "tasks#get_pdf", as: :get_tasks_pdf
  get 'get/tasks_xls', to: "tasks#get_xls", as: :get_tasks_xls
  
  get 'search', to: "tasks#search"
   
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root "projects#welcome"

end

app/models/task.rb
class Task < ApplicationRecord
  belongs_to :project
  belongs_to :user
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_action :set_task, only: %i[ show edit update destroy ]
  
  # GET /tasks or /tasks.json
  def index
    @project = Project.find(params[:project_id])
    @tasks = @project.tasks.order("id DESC")
  end

  # GET /tasks/1 or /tasks/1.json
  def show
  end

  # GET /tasks/new
  def new
    @project = Project.find(params[:project_id])
    @task = Task.new
  end

  # GET /tasks/1/edit
  def edit
    @project = Project.find(params[:project_id])
    @task = Task.find(params[:id])
  end

  # POST /tasks or /tasks.json
  def create
    @task = Task.new(task_params)
    @task.start_time = task_params["start_time(4i)"] + ":"  + task_params["start_time(5i)"]
    @task.end_time = task_params["end_time(4i)"] + ":"  + task_params["end_time(5i)"]
    respond_to do |format|
      if @task.save
        @project = @task.project 
        format.html { redirect_to project_tasks_path(@project), notice: "Task was successfully created." }
        format.json { render :show, status: :created, location: @task }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @task.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /tasks/1 or /tasks/1.json
  def update
    respond_to do |format|
      @project = @task.project 
      if @task.update(task_params)
        if @task.closed?
          hours_worked = calculate_hours_worked(@task)
          @task.update(hours_worked: hours_worked)
        end
        format.html { redirect_to project_tasks_path(@project), notice: "Task was successfully updated." }
        format.json { render :show, status: :ok, location: @task }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @task.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tasks/1 or /tasks/1.json
  def destroy
    @project = @task.project
    @task.destroy
    respond_to do |format|
      format.html { redirect_to project_tasks_path(@project), notice: "Task was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  def all_tasks
    if user_signed_in?
      @tasks = current_user.tasks.order("id DESC").page params[:page]
    else   
      @tasks = Task.all.order("id DESC").page params[:page]
    end
  end

  def get_tasks_pdf
    
    project = Project.find(params[:id])
    project_detail_html = ""
    html = File.read(Rails.root.join('app/assets/files/receipt.html'))
    
    projects.order("name ASC").each do |project|
    project_detail_html += "
                            <tr>
                              <td class='Fuente11'>#{project.name}</td>
                              <td class='Fuente11'>#{helpers.number_to_currency(project.hourly_rate, unit: '$ ', separator: ',', delimiter: '')}</td>
                              <td class='Fuente11'>#{project.currency}</td>
                              <td class='Fuente11'>#{helpers.calculate_project_hours_worked(project).round(2)}</td>
                              <td class='Fuente11'>#{helpers.calculate_project_hours_paid(project).round(2)}</td>
                              <td class='Fuente11'>#{(helpers.calculate_project_hours_worked(project)- helpers.calculate_project_hours_paid(project)).round(2)}</td>
                              <td class='Fuente11'>#{helpers.number_to_currency(helpers.calculate_project_amount_hours_paid(project), unit: '$ ', separator: ',', delimiter: '.')}</td>
                              <td class='Fuente11'>#{helpers.number_to_currency(helpers.calculate_project_amount_hours_unpaid(project), unit: '$ ', separator: ',', delimiter: '.')}</td>                                                      
                            </tr>"
    end
    
    html.gsub! "[[Website]]", "Italianolab.com"
    html.gsub! "[[Date]]", Time.now.strftime('%d/%m/%Y')
    html.gsub! "[[Item]]", project_detail_html
    html.gsub! "[[AmountPaid]]", "#{helpers.number_to_currency(helpers.calculate_project_total_amount_hours_paid, unit: '$ ', separator: ',', delimiter: '.')}"
    html.gsub! "[[AmountUnPaid]]", "#{helpers.number_to_currency(helpers.calculate_project_total_amount_hours_unpaid, unit: '$ ', separator: ',', delimiter: '.')}"
    @pdf = WickedPdf.new.pdf_from_string(html.clone,
                                         margin: {
                                             top: '0.25in',
                                             bottom: '0.25in',
                                             right: '0.25in',
                                             left: '0.25in'
                                         })

    send_data @pdf, type: 'application/pdf', disposition: 'inline'

  end
  
  def get_tasks_xls
  end
  
  def search
    
    term = params[:term]
    @tasks = Task.where("description LIKE ?", "%" + term + "%")

  end

  private
    
    def calculate_hours_worked(task)
      @task = task
      hours_worked = ((@task.start_time.to_time.seconds_until_end_of_day - @task.end_time.to_time.seconds_until_end_of_day)/60).to_f/60
      hours_worked = hours_worked.round(2)
    end

    # Use callbacks to share common setup or constraints between actions.
    def set_task
      @task = Task.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def task_params
      params.require(:task).permit(:day,
                                   :start_time,
                                   :end_time,
                                   :description,
                                   :project_id,
                                   :closed)
    end
end

app/helpers/tasks_helper.rb
module TasksHelper
  def calculate_previous_hours(project)
    if project.previous_hours_worked.nil?
      0
    else
      project.previous_hours_worked
    end
  end
end

app/views/tasks/_dialog.html.erb
<!-- Modal -->
<div class="modal fade" id="exampleModalLong" tabindex="-1" role="dialog" aria-labelledby="exampleModalLongTitle" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLongTitle">Detalle</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        ...
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-dismiss="modal">Cerrar</button>
      </div>
    </div>
  </div>
</div>

app/views/tasks/_form.html.erb
<%= form_with(model: [@project, @task], local: true) do |form| %>
  <% if @task.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@task.errors.count, "error") %> prohibited this @task from being saved:</h2>

      <ul>
        <% @task.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :day %>
    <%= form.date_select :day %>
  </div>

  <div class="field">
    <%= form.label :start_time %>
    <%= form.time_select :start_time, value: Time.now %>
  </div>

  <div class="field">
    <%= form.label :end_time %>
    <%= form.time_select :end_time %>
  </div>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_field :description %>
  </div>

  <div class="field">
    <%= form.label :project_id %>
    <%= form.select("project_id", Project.all.collect {|p| [ p.name, p.id ] }, { prompt: true, :selected => @project.id }, required: true) %>
  </div>

  <div class="field">
    <%= form.label :closed %>
    <%= form.check_box :closed %>
  </div>
  
  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/tasks/all_tasks.html.erb
<style>
th{
    font-size: 0.9em;
}
td{
    font-size: 0.8em;
}
</style>
<div class="container">

<p id="notice"><%= notice %></p>

<div class="row">
  <div class="col">
    <h1>All Tasks</h1> 
  </div>
  <div class="col text-right">
    <%= link_to "<i class='fas fa-download'></i> .xls".html_safe, get_xls_path, class: "btn btn-sm btn-success" %>
    <%= link_to "<i class='fas fa-download'></i> .pdf".html_safe, get_pdf_path, class: "btn btn-sm btn-danger" %>
  </div>
</div>

<table class="table">
  <thead>
    <tr>
      <th>Day</th>
      <th>Project</th>
      <th>Description</th>
      <th>Start time</th>
      <th>End time</th>
      <th>Hours Worked</th>
      <th>Status</th>
      <th colspan="3"></th>
    </tr>
  </thead>
  <tbody>
    <% @tasks.each do |task| %>
      <tr>
        <td><%= task.day.strftime('%d/%m/%Y') %></td>
        <td><%= link_to task.project.name, project_tasks_path(task.project) %></td>
        <td><%= task.description %></td>
        <td><%= task.start_time.in_time_zone(Time.zone).strftime('%T') %></td>
        <td><%= task.closed? ? task.end_time.strftime('%T') : "-" %></td>
        <td> <%= task.hours_worked.nil? ? "-" : task.hours_worked.round(2) %> </td>
        <td><%= task.closed? ? (link_to "Closed", "#", class: "btn btn-sm btn-success") : (link_to "Open", "#", class: "btn btn-sm btn-danger") %></td>
        <td><%#= link_to 'Show', task %></td>
        <td><%#= link_to 'Edit', edit_task_path(task) %></td>
        <td><%#= link_to 'Destroy', task, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br />

<%= paginate @tasks %>

<br />

<%= link_to 'Home', root_path, class: "btn btn-sm btn-success" %>

app/views/tasks/edit.html.erb
<h1>Editing Task</h1>

<%= render 'form', task: @task %>

<%#= link_to 'Show', @task %> |
<%#= link_to 'Back', tasks_path %>

app/views/tasks/edit.js.erb
// Add the dialog title
$('.modal h5').html(" Edit Task");

// Render the edit form
$('.modal-body').html('<%= j render("form") %>');

// Show the dynamic dialog
$('.modal').modal("show");

// Set focus to the first element
$('.modal').on('shown.bs.modal', function () {
	  $('.first_input').focus()
  })

app/views/tasks/index.html.erb
<style>
th{
    font-size: 0.9em;
}
td{
    font-size: 0.8em;
}
</style>
<div class="row">
  <div class="col">
    <% if user_signed_in? %>
      <font size="5px"><%= @project.name %></font> <%= link_to "<i class='fas fa-pen-alt'></i>".html_safe, edit_project_path(@project), remote: true %>
      <%= link_to "<i class='fas fa-times'></i>".html_safe, @project, method: :delete, data: { confirm: "Are you sure you want delete the project #{@project.name} and its tasks?" } %>
    <% else %>
      <font size="5px"><%= @project.name %></font> 
      <%= link_to "<i class='fas fa-pen-alt'></i>".html_safe, "#", data: { toggle: "modal", target: "#exampleModal" } %>
      <%= link_to "<i class='fas fa-times'></i>".html_safe, "#", data: { toggle: "modal", target: "#exampleModal" } %>
    <% end %>
  </div>
  <div class="col text-left">
    
   </div>
   <div class="col text-right">
    <p><font size="1px"><strong>Hours</strong> = Previous Hours Worked + Hours Worked = <%= calculate_previous_hours(@project).round(2) %> + <%= @project.tasks.sum(:hours_worked).round(2) %> = <strong><%= (calculate_previous_hours(@project) + @project.tasks.sum(:hours_worked)).round(2) %></strong> </font>
    </p>
  </div>
</div>


<div class="row">
  <div class="col">
    <% if user_signed_in? %>
      <%= link_to 'New Task', new_project_task_path(project_id: @project.id), class: 'btn btn-sm btn-success', remote: true %>
    <% else %>
      <%= button_tag type: 'button', class: 'btn btn-sm btn-success', data: { toggle: 'modal', target: '#exampleModal' } do %>
        New Task
      <% end %>
    <% end %>
  </div>
  <div class="col text-right">
    <%= link_to "<i class='fas fa-download'></i> .xls".html_safe, get_tasks_pdf_path, class: "btn btn-sm btn-success" %>
    <%= link_to "<i class='fas fa-download'></i> .pdf".html_safe, get_tasks_pdf_path(fomrat: :pdf), class: "btn btn-sm btn-danger" %>
  </div>
</div>

<br />

<table class="table">
  <thead>
    <tr>
      <th>Day</th>
      <th>Start time</th>
      <th>End time</th>
      <th>Description</th>
      <th>Hours Worked</th>
      <th>Status</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @tasks.each do |task| %>
      <tr>
        <td><%= task.day.nil? ? "-" : task.day.strftime('%d/%m/%Y') %></td>
        <td><%= task.start_time.strftime('%T') %></td>
        <td><%= task.closed? ? task.end_time.strftime('%T') : "-" %></td>
        <td><%= task.description %></td>
        <td><%= task.closed? ? task.hours_worked : "-" %></td>
        <td><%= 
                if task.closed? 
                  link_to 'Closed', '#', class: 'btn btn-sm btn-success'
                else
                  link_to 'Open', '#', class: 'btn btn-sm btn-danger', remote: true
                end
             %>
        </td>
        <td></td>
        <% if user_signed_in? %>
          <td><%= link_to "<i class='fas fa-pen-alt'></i>".html_safe, edit_project_task_path(@project, task), class: "btn btn-sm btn-info", remote: true %></td>
          <td><%= link_to "<i class='fas fa-times'></i>".html_safe, project_task_path(@project, task), class: "btn btn-sm btn-danger", method: :delete, data: { confirm: 'Are you sure?' } %></td>
        <% else %>
          <td>
            <%= button_tag type: 'button', class: 'btn btn-info', data: { toggle: 'modal', target: '#exampleModal' } do %>
              <i class='fas fa-pen-alt'></i>
            <% end %> 
          </td>
          <td>
            <%= button_tag type: 'button', class: 'btn btn-danger', data: { toggle: 'modal', target: '#exampleModal' } do %>
              <i class='fas fa-times'></i>
            <% end %>
          </td>
        <% end %>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

</div>

<% if user_signed_in? %>
  <%= render "dialog" %>
<% else %>
  <%= render "shared/dialog_unsigned" %>
<% end %>

app/views/tasks/new.html.erb
<div class="container">

<h1>New Task</h1>

<%= render 'form', task: @task %>

<%#= link_to 'Back', tasks_path %>

</div>

app/views/tasks/new.js.erb
// Add the dialog title
$('.modal h5').html(" Add New Task");

// Render the edit form
$('.modal-body').html('<%= j render("form") %>');

// Show the dynamic dialog
$('.modal').modal("show");

// Set focus to the first element
$('.modal').on('shown.bs.modal', function () {
	  $('.first_input').focus()
  })

app/views/tasks/search.html.erb
<p id="notice"><%= notice %></p>

<div class="container-fluid">
  <div class="row">
    <div class="col">

    <h1>Searched: <%= params[:term] %> </h1>
  
    <% if @tasks.present? %>
    
      <table class="table">
        <thead>
          <tr>
            <th>Project</th>
            <th>Day</th>
            <th>Start time</th>
            <th>End time</th>
            <th>Description</th>
            <th>Hours Worked</th>
            <th>Status</th>
            <th colspan="3"></th>
          </tr>
        </thead>

        <tbody>
          <% @tasks.each do |task| %>
            <tr>
              <td><%= link_to task.project.name, project_tasks_path(task.project) %></td>
              <td><%= task.day.nil? ? "-" : task.day.strftime('%d/%m/%Y') %></td>
              <td><%= task.start_time.strftime('%T') %></td>
              <td><%= task.closed? ? task.end_time.strftime('%T') : "-" %></td>
              <td><%= task.description %></td>
              <td><%= task.closed? ? task.hours_worked : "-" %></td>
              <td><%= 
                      if task.closed? 
                        link_to 'Closed', '#', class: 'btn btn-sm btn-success'
                      else
                        link_to 'Open', '#', class: 'btn btn-sm btn-danger', remote: true
                      end
                   %>
              </td>
              <td><%#= link_to 'Show', task %></td>
              <td><%= link_to "<i class='fas fa-pen-alt'></i>".html_safe, edit_project_task_path(task.project, task), class: "btn btn-sm btn-info", remote: true %></td>
              <td><%= link_to "<i class='fas fa-times'></i>".html_safe, project_task_path(task.project, task), class: "btn btn-sm btn-danger", method: :delete, data: { confirm: 'Are you sure?' } %></td>
            </tr>
          <% end %>
        </tbody>
      </table>

    <% else %>
      
      <p>
        No tass found search another term
      </p>

    <% end %>
    <br>
    
    <%= link_to 'Back', root_path, class: "btn btn-info" %>

    </div>
  </div>
</div>

app/views/tasks/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Day:</strong>
  <%= @task.day %>
</p>

<p>
  <strong>Start time:</strong>
  <%= @task.start_time %>
</p>

<p>
  <strong>End time:</strong>
  <%= @task.end_time %>
</p>

<p>
  <strong>Description:</strong>
  <%= @task.description %>
</p>

<p>
  <strong>Project:</strong>
  <%= @task.project_id %>
</p>

<%= link_to 'Edit', edit_task_path(@task) %> |
<%= link_to 'Back', tasks_path %>