config/routes.rb
Rails.application.routes.draw do
   
  devise_for :users
  resources :discounts
  resources :payments
  resources :payment_items

  resources :companies
  resources :projects do
    resources :tasks
  end	
  
  get 'all-tasks', to: "tasks#all_tasks"
  
  get 'get/pdf', to: "projects#get_pdf", as: :get_pdf
  get 'get/xls', to: "projects#get_xls", as: :get_xls
  
  get 'get/tasks_pdf', to: "tasks#get_pdf", as: :get_tasks_pdf
  get 'get/tasks_xls', to: "tasks#get_xls", as: :get_tasks_xls
  
  get 'search', to: "tasks#search"
   
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root "projects#welcome"

end

app/models/project.rb
class Project < ApplicationRecord

  has_many :tasks, dependent: :destroy
  has_many :payment_items, dependent: :destroy
  has_many :discounts, dependent: :destroy

  belongs_to :company
  belongs_to :user

end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  before_action :set_project, only: %i[ show edit update destroy ]

  # GET /projects or /projects.json
  def index
    if user_signed_in?
      @projects = current_user.projects
    else
      @projects = User.find(1).projects
    end
  end

  # GET /projects/1 or /projects/1.json
  def show
  end

  # GET /projects/new
  def new
    @project = Project.new
  end

  # GET /projects/1/edit
  def edit
  end

  # POST /projects or /projects.json
  def create
    @project = Project.new(project_params)

    respond_to do |format|
      if @project.save
        format.html { redirect_to root_path, notice: "Project was successfully created." }
        format.json { render :show, status: :created, location: @project }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /projects/1 or /projects/1.json
  def update
    respond_to do |format|
      if @project.update(project_params)
        format.html { redirect_to root_path, notice: "Project was successfully updated." }
        format.json { render :show, status: :ok, location: @project }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /projects/1 or /projects/1.json
  def destroy
    @project.destroy
    respond_to do |format|
      format.html { redirect_to projects_url, notice: "Project was successfully destroyed." }
      format.json { head :no_content }
    end
  end
  
  def welcome

  end

  def get_pdf
    
    projects = Project.all
    project_detail_html = ""
    html = File.read(Rails.root.join('app/assets/files/receipt.html'))
    
    projects.order("name ASC").each do |project|
    project_detail_html += "
                            <tr>
                              <td class='Fuente11'>#{project.name}</td>
                              <td class='Fuente11'>#{helpers.number_to_currency(project.hourly_rate, unit: '$ ', separator: ',', delimiter: '')}</td>
                              <td class='Fuente11'>#{project.currency}</td>
                              <td class='Fuente11'>#{helpers.calculate_project_hours_worked(project).round(2)}</td>
                              <td class='Fuente11'>#{helpers.calculate_project_hours_paid(project).round(2)}</td>
                              <td class='Fuente11'>#{(helpers.calculate_project_hours_worked(project)- helpers.calculate_project_hours_paid(project)).round(2)}</td>
                              <td class='Fuente11'>#{helpers.number_to_currency(helpers.calculate_project_amount_hours_paid(project), unit: '$ ', separator: ',', delimiter: '.')}</td>
                              <td class='Fuente11'>#{helpers.number_to_currency(helpers.calculate_project_amount_hours_unpaid(project), unit: '$ ', separator: ',', delimiter: '.')}</td>                                                      
                            </tr>"
    end
    
    html.gsub! "[[Website]]", "Italianolab.com"
    html.gsub! "[[Date]]", Time.now.strftime('%d/%m/%Y')
    html.gsub! "[[Item]]", project_detail_html
    html.gsub! "[[AmountPaid]]", "#{helpers.number_to_currency(helpers.calculate_project_total_amount_hours_paid, unit: '$ ', separator: ',', delimiter: '.')}"
    html.gsub! "[[AmountUnPaid]]", "#{helpers.number_to_currency(helpers.calculate_project_total_amount_hours_unpaid, unit: '$ ', separator: ',', delimiter: '.')}"
    @pdf = WickedPdf.new.pdf_from_string(html.clone,
                                         margin: {
                                             top: '0.25in',
                                             bottom: '0.25in',
                                             right: '0.25in',
                                             left: '0.25in'
                                         })

    send_data @pdf, type: 'application/pdf', disposition: 'inline'

  end
  
  def get_xls

  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_project
      @project = Project.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def project_params
      params.require(:project).permit(:name,
                                      :hourly_rate,
                                      :currency,
                                      :company_id,
                                      :previous_hours_worked,
                                      :previous_hours_paid)
    end

    def calculate_project_total_amount_hours_paid
      @projects = Project.all
      total_amount_projects = Array.new
      @projects.each do |project| 
        amount = calculate_project_amount_hours_paid(project)
        total_amount_projects << amount
      end
      
      total_amount_hours_paid = total_amount_projects.inject(0){|sum,x| sum + x }
    end

    def calculate_project_total_amount_hours_unpaid
      @projects = Project.all
      total_amount_projects = Array.new
      @projects.each do |project| 
        amount = calculate_project_amount_hours_unpaid(project)
        total_amount_projects << amount
      end
      
      total_amount_hours_unpaid = total_amount_projects.inject(0){|sum,x| sum + x }
    end
    
    def calculate_project_amount_hours_paid(project)
      
      @project = project
      
      unless @project.payment_items.blank?
        amount_paid = (@project.previous_hours_paid + Project.last.payment_items.sum(:hours_paid)) * @project.hourly_rate 
      else
        amount_paid = @project.previous_hours_paid * @project.hourly_rate
      end
        
    end

    def calculate_project_amount_hours_unpaid(project)
      
      @project = project
      
      total_amount = calculate_project_hours_worked(@project) * @project.hourly_rate 
      amount_paid = calculate_project_amount_hours_paid(@project)
      
      amount_unpaid = total_amount - amount_paid

    end

    def calculate_project_hours_worked(project)
      
      @project = project
    
      if @project.previous_hours_worked == 0.0
        hours_worked = project.tasks.sum(:hours_worked)
      else
        hours_worked = @project.previous_hours_worked + @project.tasks.sum(:hours_worked)
      end 
    
    end
    
    def calculate_project_hours_paid(project)
    
      @project = project
      
      if @project.previous_hours_paid == 0.0
        hours_payed = @project.payment_items.sum(:hours_paid)
      else
        hours_payed = @project.previous_hours_paid + @project.payment_items.sum(:hours_paid)
      end
    
    end

end

app/helpers/projects_helper.rb
module ProjectsHelper
  
  def calculate_project_hours_worked(project)
    
    @project = project
  
    if @project.previous_hours_worked == 0.0
      hours_worked = project.tasks.sum(:hours_worked)
    else
      hours_worked = @project.previous_hours_worked + @project.tasks.sum(:hours_worked)
    end 
  
  end
  
  def calculate_project_hours_paid(project)
  
    @project = project
    
    if @project.previous_hours_paid == 0.0
      hours_payed = @project.payment_items.sum(:hours_paid)
    else
      hours_payed = @project.previous_hours_paid + @project.payment_items.sum(:hours_paid)
    end
  
  end
  
  def calculate_project_amount_hours_paid(project)
    
    @project = project

    unless @project.payment_items.blank?
      amount_paid = (@project.previous_hours_paid + @project.payment_items.sum(:hours_paid)) * @project.hourly_rate 
    else
      amount_paid = @project.previous_hours_paid * @project.hourly_rate 
    end
    
    return amount_paid

  end

  def calculate_project_amount_hours_unpaid(project)
    
    @project = project
    
    total_amount = calculate_project_hours_worked(@project) * @project.hourly_rate 
    amount_paid = calculate_project_amount_hours_paid(@project)
    
    amount_unpaid = total_amount - amount_paid

  end
  
  def calculate_project_total_amount
    @projects = Project.all
    total_amount_projects = Array.new
    @projects.each do |project| 
      amount = calculate_project_amount_hours_paid(project) + calculate_project_amount_hours_unpaid(project)
      total_amount_projects << amount
    end
    
    total_amount = total_amount_projects.inject(0){|sum,x| sum + x }
  
  end

  def calculate_project_total_amount_hours_paid
    @projects = Project.all
    total_amount_projects = Array.new
    @projects.each do |project| 
      amount = calculate_project_amount_hours_paid(project)
      total_amount_projects << amount
    end
    
    total_amount_hours_paid = total_amount_projects.inject(0){|sum,x| sum + x }
  end

  def calculate_project_total_amount_hours_unpaid
    @projects = Project.all
    total_amount_projects = Array.new
    @projects.each do |project| 
      amount = calculate_project_amount_hours_unpaid(project)
      total_amount_projects << amount
    end
    
    total_amount_hours_unpaid = total_amount_projects.inject(0){|sum,x| sum + x }
  end

end

app/views/projects/_dialog.html.erb
<!-- Modal -->
<div class="modal fade" id="exampleModalLong" tabindex="-1" role="dialog" aria-labelledby="exampleModalLongTitle" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLongTitle">Detalle</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        ...
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-dismiss="modal">Cerrar</button>
      </div>
    </div>
  </div>
</div>

app/views/projects/_form.html.erb
<%= form_with(model: project) do |form| %>
  <% if project.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(project.errors.count, "error") %> prohibited this project from being saved:</h2>

      <ul>
        <% project.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %> <br />
    <%= form.text_field :name, required: true %>
  </div>
  
  <div class="field">
    <%= form.label :hourly_rate %> <br />
    <%= form.text_field :hourly_rate, required: true %>
  </div>
  
  <div class="field">
    <%= form.label :currency %> <br />
    <%= form.select :currency, ["MXN", "USD"] %>
  </div>
  
  <div class="field">
    <%= form.label :previous_hours_worked %> <br />
    <%= form.number_field :previous_hours_worked, step: :any %>
  </div>
  
  <div class="field">
    <%= form.label :previous_hours_paid %> <br />
    <%= form.number_field :previous_hours_paid, step: :any %>
  </div>

  <div class="field">
    <%= form.label :company_id %> <br />
    <%= form.select("company_id", Company.all.collect {|p| [ p.name, p.id ] }, { prompt: true }, required: true) %>
  </div> <br />
  

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/projects/edit.html.erb
<h1>Editing Project</h1>

<%= render 'form', project: @project %>

<%= link_to 'Show', @project %> |
<%= link_to 'Back', projects_path %>

app/views/projects/edit.js.erb
// Add the dialog title
$('.modal h5').html(" Edit Project");

// Render the edit form
$('.modal-body').html('<%= j render(partial: "form", locals: {project: @project}) %>');

// Show the dynamic dialog
$('.modal').modal("show");

// Set focus to the first element
$('.modal').on('shown.bs.modal', function () {
	  $('.first_input').focus()
  })

app/views/projects/index.html.erb
<style>
th{
    font-size: 0.9em;
}
td{
    font-size: 0.8em;
}
</style>
<div class="container">

<p id="notice"><%= notice %></p>

<div class="row">
  <div class="col">
    <h1>Projects</h1> 
  </div>
  <div class="col text-right">
    <%= link_to "<i class='fas fa-download'></i> .xls".html_safe, get_pdf_path, class: "btn btn-sm btn-success" %>
    <%= link_to "<i class='fas fa-download'></i> .pdf".html_safe, get_pdf_path(format: :pdf), class: "btn btn-sm btn-danger" %>
  </div>
</div>

<table class="table">
  <thead>
    <tr>
      <!-- <th>Begin</th> -->
      <th></th>
      <th></th>
      <th></th>
      <th colspan="3"><div align="center">HOURS</div> </th>
      <th colspan="3"><div align="center">AMOUNT</div></th>
      <th colspan="3"></th>
    </tr>
    <tr>
      <!-- <th>Begin</th> -->
      <th>Name</th>
      <th>Hourly Rate</th>
      <th>Currency</th>
      <th>Worked</th>
      <th>Paid</th>
      <th>UnPaid</th>
      <th>Paid</th>
      <th>UnPaid</th>
      <th>Discount</th>
      <th>Total</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @projects.each do |project| %>
      <tr>
        <td><%= link_to project.name, project_tasks_path(project) %></td>
        <td><%= number_to_currency(project.hourly_rate, unit: "$ ", separator: ",", delimiter: "")  %></td>
        <td><%= project.currency %></td>
        <td><%= calculate_project_hours_worked(project).round(2) %></td>
        <td><%= calculate_project_hours_paid(project).round(2) %></td>
        <td><%= (calculate_project_hours_worked(project)- calculate_project_hours_paid(project)).round(2) %></td>
        <td><%= number_to_currency(calculate_project_amount_hours_paid(project), unit: "$ ", separator: ",", delimiter: "") %></td>
        <td><%= number_to_currency(calculate_project_amount_hours_unpaid(project), unit: "$ ", separator: ",", delimiter: "")%></td>
        <td>-</td>
        <td><%= number_to_currency((project.hourly_rate * calculate_project_hours_worked(project)), unit: "$ ", separator: ",", delimiter: "") %></td>
        <td><%= project.company.nil? ? "-" : (link_to project.company.name, company_path(project.company)) %></td>
        <% if user_signed_in? %>
          <td><%= link_to "<i class='fas fa-pen'></i>".html_safe, edit_project_path(project), class: "btn btn-sm btn-info", remote: true %></td>
          <td><%= link_to "<i class='fas fa-times'></i>".html_safe, project, class: "btn btn-sm btn-danger", method: :delete, data: { confirm: 'Are you sure?' } %></td>
        <% else %>
          <td>
            <%= button_tag type: 'button', class: 'btn btn-sm btn-info', data: { toggle: 'modal', target: '#exampleModal' } do %>
              <i class='fas fa-pen'></i>
            <% end %> 
          </td>
          <td>
            <%= button_tag type: 'button', class: 'btn btn-sm btn-danger', data: { toggle: 'modal', target: '#exampleModal' } do %>
              <i class='fas fa-times'></i>
            <% end %>
          </td>
        <% end %>
      </tr>
    <% end %>
      <tr>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td><%= number_to_currency(calculate_project_total_amount_hours_paid, unit: "$ ", separator: ",", delimiter: ".") %></td>
        <td><%= number_to_currency(calculate_project_total_amount_hours_unpaid, unit: "$ ", separator: ",", delimiter: ".") %></td>
        <td></td>
        <td></td>
        <td></td>
      </tr>
  </tbody>
</table>

<br>

<% unless user_signed_in? %>
    <h1>
      <%= button_tag type: 'button', class: 'btn btn-sm btn-success', data: { toggle: 'modal', target: '#exampleModal' } do %>
        New Project
      <% end %> |
      <%= link_to 'All Tasks', all_tasks_path, class: "btn btn-sm btn-warning" %> </h1>
      <%= render 'shared/dialog_unsigned' %>
  <% else %>
    <h1><%= link_to 'New Project', new_project_path, class: "btn btn-sm btn-success", remote: true %> | 

    <%= link_to 'All Tasks', all_tasks_path, class: "btn btn-sm btn-warning" %> </h1>
  <% end %>
</div>

<%= render "dialog" %>

app/views/projects/new.html.erb
<h1>New Project</h1>

<%= render 'form', project: @project %>

<%= link_to 'Back', projects_path %>

app/views/projects/new.js.erb
// Add the dialog title
$('.modal h5').html(" Add New Project");

// Render the edit form
$('.modal-body').html('<%= j render(partial: "form", locals: {project: @project}) %>');

// Show the dynamic dialog
$('.modal').modal("show");

// Set focus to the first element
$('.modal').on('shown.bs.modal', function () {
	  $('.first_input').focus()
  })

app/views/projects/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @project.name %>
</p>

<%= link_to 'Edit', edit_project_path(@project) %> |
<%= link_to 'Back', projects_path %>

app/views/projects/welcome.html.erb
<p><hr></p>
<div class="jumbotron">
  <h1 class="display-4">Hi, world!</h1>
  <p class="lead">This is a basic open source time tracking web app helps you easily track time spent on tasks.</p>
  <hr class="my-4">
  <p>Begin to start a new project.</p>
  <% unless user_signed_in? %>
    <p class="lead">
      <%= button_tag type: 'button', class: 'btn btn-primary', data: { toggle: 'modal', target: '#exampleModal' } do %>
        Add Project
      <% end %>
    </p>
      <small>Or if you don't have an account yet, please <%= link_to "Sign Up", new_user_registration_path %>.</small>
      <%= render 'shared/dialog_unsigned' %>
  <% else %>
    <p class="lead">
      <%= link_to "Add Project", new_project_path, role: "button", class: "btn btn-primary btn-lg", remote: true %>
    </p>
      <%= render 'dialog' %>
  <% end %>
</div>