config/routes.rb
Rails.application.routes.draw do
   
  devise_for :users
  resources :discounts
  resources :payments
  resources :payment_items

  resources :companies
  resources :projects do
    resources :tasks
  end	
  
  get 'all-tasks', to: "tasks#all_tasks"
  
  get 'get/pdf', to: "projects#get_pdf", as: :get_pdf
  get 'get/xls', to: "projects#get_xls", as: :get_xls
  
  get 'get/tasks_pdf', to: "tasks#get_pdf", as: :get_tasks_pdf
  get 'get/tasks_xls', to: "tasks#get_xls", as: :get_tasks_xls
  
  get 'search', to: "tasks#search"
   
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root "projects#welcome"

end

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <a class="navbar-brand" href="#">HourTask!</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active">
        <%= link_to "Home<span class='sr-only'>(current)</span>".html_safe, root_path, class: "nav-link" %>
      </li>
      <li class="nav-item">
        <%= link_to "Projects".html_safe, projects_path, class: "nav-link" %>
      </li>
      <li class="nav-item">
        <%= link_to "Tasks".html_safe, all_tasks_path, class: "nav-link" %>
      </li>
      <li class="nav-item">
        <%= link_to "Companies".html_safe, companies_path, class: "nav-link" %>
      </li>
      <li class="nav-item">
        <%= link_to "Payments".html_safe, payments_path, class: "nav-link" %>
      </li>
      <li class="nav-item">
        <%= link_to "Discounts".html_safe, discounts_path, class: "nav-link" %>
      </li>
    </ul>
    <% if user_signed_in? %>
      <span class="navbar-text" style="padding-right:10px;">
        <%= link_to "Logout".html_safe, destroy_user_session_path, method: :delete, class: "btn btn-outline-danger my-2 my-sm-0" %>
      </span>
    <%= form_tag("/search", :method => "get", class: "form-inline my-2 my-lg-0") do %>
      <%= search_field_tag "term", nil, placeholder: "Some Task", class: "form-control mr-sm-2" %>
      <%= submit_tag "Search Task", {name: nil, class: "btn btn-outline-success my-2 my-sm-0"} %>
    <% end %>
    <% else %>
      <span class="navbar-text">
        <%= link_to "Login".html_safe, new_user_session_path, class: "btn btn-outline-success my-2 my-sm-0" %>
      </span>
    <% end %>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Hourtask</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    
    <%= render 'layouts/navbar' %>
    <div class="d-flex flex-column min-vh-100">
    <div class="container">
      
      <div class="row">
        <div class="col">
          <%= flash_messages %>
        </div>
      </div>

      <%= yield %>
    </div>
      <footer class="footer mt-auto py-3 bg-light">
      Hourtask &copy; <%= Time.new.year %> an <%= link_to 'Astr0surf3r Open Source project', 'https://github.com/Astr0surf3r/hourtask' %>
      </footer>
    </div>

  </body>
</html>

app/views/layouts/pdf.html.erb
<html>
<head>
   <meta charset="UTF-8">
    <style>
        body {
            font-family: Arial, Helvetica, sans-serif;
            font-size: 10px;
            word-wrap: break-word;
        }

        .celdaNormal {
            line-height: 12px;
            border-radius: 0.10px;
            border-style: solid;
            border-width: 1px;
            padding: 0.1em;
            position: relative;
            text-align: left;;
            font-size: 10px;
            border-color: #BBB;
            font-weight: normal;
            word-wrap: break-word;
        }

        .celdaDetalle {
            background: #fff;
            border-style: solid;
            border-width: 0.25px;
            padding: 0px;
            margin: 0px;
            position: relative;
            text-align: left;;
            font-size: 12px;
            border-color: #CCC;
            word-wrap: break-word;
        }

        .celdaNormalCentro {
            line-height: 12px;
            border-radius: 0.10px;
            border-style: solid;
            border-width: 1px;
            padding: 0.5em;
            position: relative;
            text-align: center;;
            font-size: 12px;
            border-color: #BBB;
            font-weight: normal;
            word-wrap: break-word;
        }

        .celdaNormalDerecha {
            line-height: 12px;
            padding: 0.5em;
            position: relative;
            text-align: right;;
            font-size: 10px;
            border-color: #BBB;
            font-weight: normal;
            word-wrap: break-word;
        }

        .celdaPeqDerecha {
            line-height: 12px;
            padding: 0.5em;
            position: relative;
            text-align: right;;
            font-size: 9px;
            border-color: #BBB;
            font-weight: normal;
            word-wrap: break-word;
        }

        .celdaNormalBlanca {
            line-height: 12px;
            border-style: solid;
            border-width: 0px;
            padding: 0;
            position: relative;
            text-align: left;;
            font-size: 11px;
        }

        .celdaTituloBlanca {
            line-height: 12px;
            border-style: solid;
            border-width: 0px;
            padding: 0;
            position: relative;
            text-align: left;
            font-size: 10px;
        }

        .celdaNormalBlancaDer {
            line-height: 12px;
            border-style: solid;
            border-width: 0px;
            padding: 0;
            position: relative;
            text-align: right;
            font-size: 10px;
            font-weight: normal;
        }

        .celdaNormalBlancaCen {
            line-height: 12px;
            border-style: solid;
            border-width: 0px;
            padding: 0;
            position: relative;
            text-align: center;
            font-size: 10px;
            font-weight: normal;
            word-wrap: break-word;
        }

        .celdaBold {
            border-radius: 0.10px;
            border-style: solid;
            border-width: 1px;
            padding: 0.5em;
            position: relative;
            text-align: left;
            font-size: 12px;
            border-color: #BBB;
            font-weight: bold;
            word-wrap: break-word;
        }

        .celdaFolio {
            padding: 0.2em;
            position: relative;
            text-align: right;
            font-size: 16px;
            border-color: #BBB;
            font-weight: bold;
            color: #900;
            margin-right: 3px;
        }

        .celdaPagare {
            border-radius: 0.10px;
            border-style: solid;
            border-width: 1px;
            padding: 0.5em;
            position: relative;
            text-align: left;
            font-size: 10px;
            border-color: #BBB;
            word-wrap: break-word;
        }

        .celdaEncabezado {
            line-height: 15px;
            background: #000;
            border-color: #BBB;
            position: relative;
            text-align: center;
            font-weight: bold;
            font-size: 12px;
            word-wrap: break-word;
            color: #FFF
        }

        .celdaBlanca {
            margin: 0;
            padding: 0;
            border: none;
        }

        .Fuente11 {
            font-size: 11px
        }

        .Fuente10 {
            font-size: 10px
        }

        .Fuente9 {
            font-size: 9px
        }

        .Fuente8 {
            font-size: 8px
        }

        .Derecha {
            text-align: right;
        }

        .BordeInf {
            border-bottom-style: solid;
            border-bottom-color: #000;
            border-bottom-width: thin;
        }

        .Superior {
            vertical-align: text-top;
        }
    </style>
</head>

<body>
<table width="100%" height="850px" border="0" cellspacing="0" cellpadding="0">
<table>
 <tr>
   <td>Ciao</td>
   <td>Presto</td>
 </tr>
</table>
</body>
</html>